export enum ActionTypeEnum {
  NASA_GET_APOD = 'NASA_GET_APOD',
  WEATHER_GET_CURRENT = 'WEATHER_GET_CURRENT',
  TIMER = 'TIMER',
  PULL_REQUEST_CREATED = 'PULL_REQUEST_CREATED',
  ISSUE_OPENED = 'ISSUE_OPENED',
  BRANCH_MERGED = 'BRANCH_MERGED',
  PULL_REQUEST_REVIEW_REQUESTED = 'PULL_REQUEST_REVIEW_REQUESTED',
  PULL_REQUEST_REVIEW_REQUEST_REMOVED = 'PULL_REQUEST_REVIEW_REQUEST_REMOVED',
  BRANCH_CREATED = 'BRANCH_CREATED',
  BRANCH_DELETED = 'BRANCH_DELETED',
  STAR_ADDED = 'STAR_ADDED',
  STAR_REMOVED = 'STAR_REMOVED',
}
