name: NestJS CI

on:
    push:
        branches:
            - main
            - dev
            - AW-35-Tests-unitaires
        paths:
            - "api/**"
    pull_request:
        branches:
            - main
            - dev
        paths:
            - "api/**"

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4.0.0
              with:
                  node-version: "21"

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install Dependencies
              run: pnpm install --no-frozen-lockfile
              working-directory: ./api

            - name: Build
              run: pnpm run build
              working-directory: ./api

              # Get the output of ./test.sh
            - name: Run Tests
              run: |
                  chmod +x ./test.sh
                  if ! ./test.sh; then
                      exit 1
                  fi
              working-directory: ./api
