name: Flutter APK Build

on:
    push:
        branches:
            - main
            - dev
            - AW-35-Tests-unitaires
        paths:
            - "flutter_area/**"
    pull_request:
        branches:
            - main
            - dev
        paths:
            - "flutter_area/**"

jobs:
    release-create:
        permissions: write-all
        runs-on: ubuntu-latest

        outputs:
            release: ${{ steps.release.outputs.release_tag }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - id: release
              name: Create Release
              if: github.repository != 'EpitechPromo2026/B-DEV-500-TLS-5-2-area-valentin.gegoux.git'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  export GITHUB_OUTPUT=$GITHUB_OUTPUT
                  bash ./.github/workflows/release.sh "${{ env.BRANCH }}"

    build-apk:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2.12.0
              with:
                  flutter-version: "3.16"

            - name: Install Dependencies
              run: flutter pub get
              working-directory: ./flutter_area

            - name: Build APK
              run: flutter build apk --release
              working-directory: ./flutter_area

            - name: Upload APK
              uses: actions/upload-artifact@v3.1.3
              with:
                  name: maker.apk
                  path: ./flutter_area/build/app/outputs/flutter-apk/app-release.apk

            - name: Extract Tag Name
              id: tag_name
              run: |
                  echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
              env:
                  GITHUB_REF: ${{ github.ref }}

            - name: Upload To Release
              working-directory: ./flutter_area
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release upload ${{ needs.release-create.outputs.release }} ./flutter_area/build/app/outputs/flutter-apk/app-release.apk
