name: Flutter APK Build

on:
    push:
        branches:
            - main
            - dev
            - AW-35-Tests-unitaires
        paths:
            - "flutter_area/**"
    pull_request:
        branches:
            - main
            - dev
        paths:
            - "flutter_area/**"

jobs:
    build-apk:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Set up Flutter
              uses: subosito/flutter-action@v2.12.0
              with:
                  flutter-version: "3.16"

            - name: Install Dependencies
              run: flutter pub get
              working-directory: ./flutter_area

            - name: Build APK
              run: flutter build apk --release
              working-directory: ./flutter_area

            - name: Upload APK
              uses: actions/upload-artifact@v3.1.3
              with:
                  name: maker.apk
                  path: ./flutter_area/build/app/outputs/flutter-apk/app-release.apk

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false

            - name: Upload To Release
              working-directory: ./flutter_area
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  gh release upload ${{ steps.create_release.outputs.upload_url }} ./flutter_area/build/app/outputs/flutter-apk/app-release.apk
